import service1 from "../../public/icons/service1.png";
import service10 from "../../public/icons/service10.png";
import service11 from "../../public/icons/service11.png";
import service12 from "../../public/icons/service12.png";
import service2 from "../../public/icons/service2.png";
import service3 from "../../public/icons/service3.png";
import service4 from "../../public/icons/service4.png";
import service5 from "../../public/icons/service5.png";
import service6 from "../../public/icons/service6.png";
import service7 from "../../public/icons/service7.png";
import service8 from "../../public/icons/service8.png";
import service9 from "../../public/icons/service9.png";

import product1 from "../../public/images/store/products/product1.png";
import product2 from "../../public/images/store/products/product2.png";
import product3 from "../../public/images/store/products/product3.png";
import product4 from "../../public/images/store/products/product4.png";
import product5 from "../../public/images/store/products/product5.png";
import product6 from "../../public/images/store/products/product6.png";
import product7 from "../../public/images/store/products/product7.png";
import product8 from "../../public/images/store/products/product8.png";
import product9 from "../../public/images/store/products/product9.png";
import product10 from "../../public/images/store/products/product10.png";

export const plansY = [
  {
    title: "silverPlan.title",
    price: "800",
    features: [
      "silverPlan.features.feature1",
      "silverPlan.features.feature2",
      "silverPlan.features.feature3",
      "silverPlan.features.feature4",
      "silverPlan.features.feature5",
      "silverPlan.features.feature6",
      "silverPlan.features.feature7",
    ],
    link: "https://store.inbrief.click/subsription/منتج/الباقة-الفضية/",
    USD: "250",
    SAR: "800",
    OMR: "90",
    KD: "80",
  },
  {
    title: "goldPlan.title",
    price: "2000",
    features: [
      "goldPlan.features.feature1",
      "goldPlan.features.feature2",
      "goldPlan.features.feature3",
      "goldPlan.features.feature4",
      "goldPlan.features.feature5",
      "goldPlan.features.feature6",
      "goldPlan.features.feature7",
      "goldPlan.features.feature8",
      "goldPlan.features.feature9",
    ],
    link: "https://store.inbrief.click/subsription/منتج/الباقة-الذهبية/",
    USD: "490",
    SAR: "2000",
    OMR: "150",
    KD: "150",
  },
];

export const plansM = [
  {
    title: "silverPlan.title",
    price: "70",
    features: [
      "silverPlan.features.feature1",
      "silverPlan.features.feature2",
      "silverPlan.features.feature3",
      "silverPlan.features.feature4",
      "silverPlan.features.feature5",
      "silverPlan.features.feature6",
      "silverPlan.features.feature7",
    ],
    link: "https://store.inbrief.click/subsription/منتج/الباقة-الفضية-شهري/",
    USD: "22",
    SAR: "70",
    OMR: "9",
    KD: "8",
  },
  {
    title: "goldPlan.title",
    price: "2000",
    features: [
      "goldPlan.features.feature1",
      "goldPlan.features.feature2",
      "goldPlan.features.feature3",
      "goldPlan.features.feature4",
      "goldPlan.features.feature5",
      "goldPlan.features.feature6",
      "goldPlan.features.feature7",
      "goldPlan.features.feature8",
      "goldPlan.features.feature9",
    ],
    link: "https://store.inbrief.click/subsription/منتج/الباقة-الذهبية-شهري/",
    USD: "45",
    SAR: "180",
    OMR: "14",
    KD: "15",
  },
];

export const SERVICES = [
  {
    icon: service1,
    title: "addons.whatsapp",
    description: "addons.whatsapp_desc",
    USD: "18",
    SAR: "70",
    OMR: "7",
    KD: "6",
  },
  {
    icon: service2,
    title: "addons.sms",
    description: "addons.sms_desc",
    USD: "10",
    SAR: "35",
    OMR: "4",
    KD: "4",
  },
  {
    icon: service3,
    title: "addons.chatbot",
    description: "addons.chatbot_desc",
    USD: "18",
    SAR: "70",
    OMR: "7",
    KD: "6",
  },
  {
    icon: service4,
    title: "addons.pos",
    description: "addons.pos_desc",
    USD: "18",
    SAR: "70",
    OMR: "7",
    KD: "6",
  },
  {
    icon: service5,
    title: "addons.driver",
    description: "addons.driver_desc",
    USD: "18",
    SAR: "70",
    OMR: "7",
    KD: "6",
  },
  {
    icon: service6,
    title: "addons.mobile_app",
    description: "addons.mobile_app_desc",
    USD: "120",
    SAR: "425",
    OMR: "35",
    KD: "35",
  },
  {
    icon: service7,
    title: "addons.consultant",
    description: "addons.consultant_desc",
    USD: "130",
    SAR: "500",
    OMR: "40",
    KD: "40",
  },
  {
    icon: service8,
    title: "addons.content_upload",
    description: "addons.content_upload_desc",
    USD: "85",
    SAR: "300",
    OMR: "25",
    KD: "25",
  },
  {
    icon: service9,
    title: "addons.seo",
    description: "addons.seo_desc",
    USD: "130",
    SAR: "500",
    OMR: "40",
    KD: "40",
  },
  {
    icon: service10,
    title: "addons.marketing_consultant",
    description: "addons.marketing_consultant_desc",
    USD: "130",
    SAR: "500",
    OMR: "40",
    KD: "40",
  },
  {
    icon: service11,
    title: "addons.table_reservation",
    description: "addons.table_reservation_desc",
    USD: "18",
    SAR: "70",
    OMR: "7",
    KD: "6",
  },
  {
    icon: service12,
    title: "addons.multi_vendor",
    description: "addons.multi_vendor_desc",
    USD: "50",
    SAR: "200",
    OMR: "18",
    KD: "16",
  },
];

export const PRODUCTS = [
  { title: "perfumes", image: product1 },
  { title: "electronic_devices", image: product2 },
  { title: "abayas_fashion", image: product3 },
  { title: "furniture_home", image: product4 },
  { title: "children_toys", image: product5 },
  { title: "restaurants_cafes", image: product6 },
  { title: "digital_products", image: product7 },
  { title: "accessories", image: product8 },
  { title: "gifts_decor", image: product9 },
  { title: "household_items", image: product10 },
];

export const FEATURES = [
  "features.feature1",
  "features.feature2",
  "features.feature3",
  "features.feature4",
  "features.feature5",
  "features.feature6",
  "features.feature7",
  "features.feature8",
  "features.feature9",
  "features.feature10",
  "features.feature11",
  "features.feature12",
  "features.feature13",
  "features.feature14",
  "features.feature15",
  "features.feature16",
  "features.feature17",
  "features.feature18",
  "features.feature19",
  "features.feature20",
  "features.feature21",
  "features.feature22",
  "features.feature23",
  "features.feature24",
  "features.feature25",
  "features.feature26",
  "features.feature27",
  "features.feature28",
];

export const PACKAGES = [
  {
    title: "silver",
    features: [
      "Unlimited",
      "Unlimited",
      "Unlimited",
      "1",
      "checked",
      "checked",
      "checked",
      "OneLanguage",
      "",
      "threePages",
      "checked",
      "checked",
      "checked",
      "checked",
      "",
      "checked",
      "checked",
      "checked",
      "branch",
      "",
      "checked",
      "checked",
      "checked",
      "checked",
      "checked",
      "checked",
      "checked",
      "workingHours",
    ],
    link: "https://store.inbrief.click/subsription/منتج/الباقة-الفضية/",
  },
  {
    title: "gold",
    features: [
      "Unlimited",
      "Unlimited",
      "Unlimited",
      "3",
      "checked",
      "MultipleGateways",
      "checked",
      "twoLanguages",
      "checked",
      "tenPages",
      "checked",
      "checked",
      "checked",
      "checked",
      "checked",
      "checked",
      "checked",
      "checked",
      "threeBranches",
      "checked",
      "checked",
      "checked",
      "checked",
      "checked",
      "checked",
      "checked",
      "checked",
      "24Hours",
    ],
    link: "https://store.inbrief.click/subsription/منتج/الباقة-الذهبية/",
  },
];
